services:
  db:
    image: pgvector/pgvector:pg18-trixie
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: bonfire
      POSTGRES_PASSWORD: bonfire
      POSTGRES_DB: bonfire
    volumes:
      - pgdata:/var/lib/postgresql
volumes:
  pgdata:
