services:
  db:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_USER: bonfire
      POSTGRES_PASSWORD: bonfire
      POSTGRES_DB: bonfire
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql

volumes:
  db:
